version: '3'

services:
  app:
    image: greenfrontend/test-env:v1
    entrypoint: /bin/sh
    command:
      - "-c"
      - "node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 8080
